name: foodtrack
description: FoodTrack App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.2

  # Local Storage
  shared_preferences: ^2.5.3

  # State Management
  provider: ^6.1.5+1
  intl: ^0.20.2
  fl_chart: ^0.68.0

  # External API Integration
  http: ^1.2.2

  # Typography
  google_fonts: ^6.2.1

  # Push Notifications
  flutter_local_notifications: ^18.0.1

  # Google Sign‑In
  google_sign_in: ^6.2.0

  # Audio Player
  audioplayers: ^6.0.0

  # Image Picker & Firebase Storage (for profile photo upload)
  image_picker: ^1.1.2
  firebase_storage: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/sounds/